# Server configuration
server:
  port: 8089
  servlet:
    context-path: /

# Spring configuration
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: my-consumer-group
      topic: my-topic
      auto-offset-reset: earliest
      max-poll-records: 100
      max-poll-interval-ms: 300000
      session-timeout-ms: 10000
      heartbeat-interval-ms: 3000
  minio:
    url: http://localhost:9000        # MinIO服务器地址
    access-key: minioadmin            # 访问密钥
    secret-key: minioadmin            # 秘密密钥
    bucket: test                  # 默认桶名称
  datasource:
    url: jdbc:dm://LOCALHOST:5236/TESTDB
    username: SYSDBA
    password: SYSDBA
    driver-class-name: dm.jdbc.driver.DmDriver
  mybatis-plus:
    mapper-locations: classpath:com/example/demo/**/*.xml
    type-aliases-package: com.example.demo.demo1.entities

# Knife4j configuration
knife4j:
  enable: true
  setting:
    language: en-US
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: Models
    enable-version: false
    enable-reload-cache-parameter: false
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-request-cache: true
    enable-search: true
    enable-debug: true
    enable-open-api: false
    enable-group: true
  basic:
    enable: false
    username: admin
    password: 123456
  production: false


